### ISSUE TITLE
Dionaea Tagging

### ISSUE THREAD

**Issue by ariddi7** [CommunityHoneyNetwork/CHN-Server#151]
The tagging function in dionaea doesn't seem to work. I think this might be due to square brackets being inserted in 

> /opt/dionaea/etc/dionaea/ihandlers-available/hpfeeds.yaml

```
- name: hpfeeds
  config:
    server: "server.example"
    port: 10000
    ident: "ident.example"
    secret: "secret.example"
    tags: [hpname:test]
    # dynip_resolve: enable to lookup the sensor ip through a webservice
#    dynip_resolve:
```

Essentially, when you add something to the tagging through dionaea.sysconfig it then breaks all logging though CHN. As soon as you remove the tag it will work again.

```
dionaea.sysconfig
#
# This can be modified to change the default setup of the dionaea unattended installation

DEBUG=false

# IP Address of the honeypot
# Leaving this blank will default to the docker container IP
IP_ADDRESS=

CHN_SERVER="https://server.example"
DEPLOY_KEY=5V8OnUpB

# Network options
LISTEN_ADDRESSES="0.0.0.0"
LISTEN_INTERFACES="eth0"


# Service options
# blackhole, epmap, ftp, http, memcache, mirror, mongo, mqtt, mssql, mysql, pptp, sip, smb, tftp, upnp
SERVICES=(blackhole epmap ftp http memcache mirror mongo mqtt pptp sip smb tftp upnp)

DIONAEA_JSON="/etc/dionaea/dionaea.json"

# Logging options
HPFEEDS_ENABLED=true
FEEDS_SERVER="server.example"
FEEDS_SERVER_PORT=10000

# Comma separated tags for honeypot
TAGS="hpname:test"
```
